version: 0.0
os: linux
files:
  - source: test-webapp.war
    destination: /home/ubuntu/tomcat7/webapps
  - source: config/tomcat-users.xml
    destination: /home/ubuntu/tomcat7/config

permissions:
  - object: /home/ubuntu/tomcat7/webapps/test-webapp.war
    group: ubuntu
    owner: ubuntu
    mode: 644
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop-app.sh
      runas: ubuntu
      timeout: 120
  ApplicationStart:
    - location: scripts/start-app.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-install.sh
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: ubuntu
      timeout: 300