version: 0.2

phases:
  build:
    commands:
      - cd test-webapp
      - mvn compile package
      - mv target/test-webapp-1.0-SNAPSHOT.war ../test-webapp.war
artifacts:
  files:
    - test-webapp.war
    - appspec.yml
    - scripts/*.sh
    - config/*
