version: 0.2

phases:
  build:
    commands:
      - cd test-webapp
      - mvn compile package
artifacts:
  files:
    - test-webapp/target/test-webapp-1.0-SNAPSHOT.war
    - appspec.yml
    - scripts/*.sh
